web/router.ex
defmodule Exerself.Router do
  use Exerself.Web, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Exerself.Auth
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug Exerself.Auth
  end

  scope "/auth", Exerself do
    pipe_through [:browser]

    get "/:provider", AuthController, :request
    get "/:provider/callback", AuthController, :callback
    post "/:provider/callback", AuthController, :callback
    delete "/logout", AuthController, :delete
  end

  scope "/", Exerself do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
  end

  # Other scopes may use custom stacks.
  scope "/api", Exerself do
    pipe_through :api
    
    resources "/stationary_bike_rides", StationaryBikeRideController, except: [:new, :edit, :show]
  end
end

web/templates/page/index.html.eex
  <%= if @current_user do %>
    <div id="main"></div>

    <script src='<%= static_path(@conn, "/js/uilab.js") %>'></script>
    <script>
      var flags = {
        type: "Panel",
        children: {
          heading: {
            type: "Title",
            text: "Exerself",
            level: 3,
            classes: ["panel-title"]
          },
          body: {
            type: "Container",
            children: {
              row: {
                type: "Row",
                children: {
                  index: {
                    type: "Link",
                    text: "List rides",
                    classes: [],
                    <!-- url: "#<%= stationary_bike_ride_url(@conn, :index) %>" -->
                    url: "#api/stationary_bike_rides"
                  }
                }
              }
            }
          }
        }
      };
    </script>
    <script>
      var node = document.getElementById('main');
      var app = Elm.Main.embed(node, flags);
    </script>

  <% else %>
  <div class="jumbotron">
    <h2><%= gettext "Welcome to %{name}", name: "Exerself" %></h2>
    <p class="lead">Get moving</p>
  </div>

  <div class="row marketing">
    <a class="btn btn-primary btn-lg" href="/auth/google">
      <i class="fa fa-google"></i>
      Sign in with Google
    </a>
  </div>
<% end %>